Terraform-1
otus-devops-2019-05/kalinkina_infra pull request #5
Opened 2019-08-08 08:07 UTC by kalinkina

# Выполнено ДЗ №

 - [X] Основное ДЗ
 - [X] Задание со *
-  [ ] Задание со **
## В процессе сделано:
 - Запущен reddit-app с помощью terraform
 - переменные вынесены в отдельные файлы

## Как запустить проект:
 - terraform apply

## Как проверить работоспособность:
 - перейти по ссылке http://104.155.28.253:9292

## PR checklist
 - [X] Выставил label с темой домашнего задания

2019-08-08 11:41 UTC, kalinkina commented
А это нормально, что мы вроде как пользуемся версией терраформа 0.11.11, а в вашем докерфайле прописана версия 0.11.7 https://github.com/express42/otus-homeworks/blob/2019-02/Dockerfile ?
 Просто из-за этого не проходили тесты в пул реквесте https://github.com/otus-devops-2019-05/kalinkina_infra/pull/5 
 ```  ×  terraform: Run terraform validate (3 failed)
     ✔  File terraform/terraform.tfvars.example should exist
     ×  Command: `cd terraform && terraform init && terraform validate -var-file=terraform.tfvars.example` stdout should match "Terraform has been successfully initialized!"
     expected "" to match "Terraform has been successfully initialized!"
     ×  Command: `cd terraform && terraform init && terraform validate -var-file=terraform.tfvars.example` stderr should eq ""
     
     expected: ""
          got: "\e[31m\n\e[1m\e[31mError: \e[0m\e[0m\e[1mThe currently running version of Terraform doesn't meet the...n\n  Module: root\n  Required version: 0.11.11\n  Current version: 0.11.7\e[0m\n\n\e[0m\e[0m\e[0m\n"  ```

2019-08-08 12:39 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Хорошее ридми у вас получилось. Касательно ошбки в тестах. Терраформ подставляет через переменную путь к ssh ключу. У вас путь, точнее имя ключа, отличаются от того который используется в методичке и соответственно в тесте. Как только будет исправлена эта ошибка (написал коммент к файлу), все должно заработать. Пока возвращаю на доработку =)

2019-08-08 12:39 UTC, mrgreyves commented on terraform/terraform.tfvars.example
> +public_key_path = "~/.ssh/id_rsa_test.pub"
Стоит обратить внимание =)

2019-08-08 22:30 UTC, kalinkina commented on terraform/terraform.tfvars.example
> +public_key_path = "~/.ssh/id_rsa_test.pub"
Спасибо за пояснение. Ридми, конечно, феерический)

2019-08-09 05:57 UTC, mrgreyves commented on terraform/terraform.tfvars.example
> +public_key_path = "~/.ssh/id_rsa_test.pub"
Пожалуйста. Да нормальный ридми, ну =)

2019-08-09 05:59 UTC, mrgreyves approved these changes
Здравствуйте!) Проверил ваше дз. По поводу версий terraform перепроверю методичку. ДЗ принимаю!=)

2019-08-09 07:26 UTC, merged